import { Link, useParams } from 'react-router-dom';
import AdminLayout from '../AdminLayout';
import { ErrorAlert } from '../catalog/CatalogParts';
import { failureMessage } from '../catalog/catalogApi';
import { formatDateTime, formatMoney, shortId } from '../reports/formatters';
import { DayStatusBadge, Facts, Money, PaymentBreakdown, Panel, Variance, useLoad, useSignIn } from './historyParts';

function ZReadingPanel({ reading }) {
    const totals = reading.totals_snapshot;

    return (
        <Panel title={`Z-reading #${totals.z_counter}`} note="The end-of-day figures, fixed when the day was closed. They are never recalculated.">
            <div className="space-y-4">
                <Facts
                    items={[
                        ['Business date', reading.business_date],
                        ['Generated', formatDateTime(reading.generated_at)],
                        ['Covers', `${formatDateTime(reading.from_at)} to ${formatDateTime(reading.to_at)}`],
                        ['Generated by', <span key="g" title={reading.generated_by}>{shortId(reading.generated_by)}</span>],
                        ['Reset counter', String(totals.reset_counter)],
                    ]}
                />
                <Facts
                    items={[
                        ['Gross sales', formatMoney(totals.gross_sales)],
                        ['Taxable sales', formatMoney(totals.taxable_sales)],
                        ['VAT-exempt sales', formatMoney(totals.vat_exempt_sales)],
                        ['Zero-rated sales', formatMoney(totals.zero_rated_sales)],
                        ['Non-VAT sales', formatMoney(totals.non_vat_sales)],
                        ['VAT amount', formatMoney(totals.vat_amount)],
                        ['Voids', formatMoney(totals.void_total)],
                        ['Refunds', formatMoney(totals.refund_total)],
                    ]}
                />
                <Facts
                    items={[
                        ['Accumulated sales before', formatMoney(totals.accumulated_grand_total_sales_before)],
                        ['Accumulated sales after', formatMoney(totals.accumulated_grand_total_sales_after)],
                    ]}
                />
                <div>
                    <p className="mb-1 text-[11px] uppercase tracking-wide text-slate-500">Payments by method</p>
                    <PaymentBreakdown breakdown={totals.payment_breakdown} />
                </div>
            </div>
        </Panel>
    );
}

/**
 * /admin/fiscal-days/:fiscalDayId -- fiscalDayGet, the shifts that made up the day (shiftList filtered to it)
 * and, once the day is closed, its Z-reading (fiscalDayZReadingGet).
 */
export default function FiscalDayDetailPage() {
    const { fiscalDayId } = useParams();
    const signIn = useSignIn();
    const day = useLoad(`/api/v1/fiscal-days/${fiscalDayId}`);
    const shifts = useLoad(day.data ? `/api/v1/shifts?fiscal_day_id=${fiscalDayId}&per_page=100` : null);
    const zReading = useLoad(day.data?.status === 'CLOSED' ? `/api/v1/fiscal-days/${fiscalDayId}/z-reading` : null);

    const current = day.data;

    return (
        <AdminLayout title="Fiscal day" requiredCapability="REPORT_VIEW" wide>
            <p className="mb-3 text-xs">
                <Link to="/admin/fiscal-days" className="text-emerald-400 hover:underline">
                    &larr; All fiscal days
                </Link>
            </p>

            {day.failure && (
                <ErrorAlert
                    message={day.failure.status === 404 ? 'This fiscal day could not be found.' : failureMessage(day.failure, 'The fiscal day could not be loaded.')}
                    onRetry={[401, 403, 404].includes(day.failure.status) ? undefined : day.reload}
                    onSignIn={day.failure.status === 401 ? signIn : undefined}
                />
            )}

            {day.loading && !current && !day.failure && <div className="h-40 animate-pulse rounded bg-slate-900" aria-busy="true" aria-label="Loading fiscal day" />}

            {current && (
                <>
                    <div className="mb-4 flex flex-wrap items-center gap-3">
                        <h2 className="text-xl font-semibold text-slate-100">Business day {current.business_date}</h2>
                        <DayStatusBadge status={current.status} />
                    </div>

                    <Panel title="The day">
                        <Facts
                            items={[
                                ['Terminal', <span key="t" title={current.terminal_id}>{shortId(current.terminal_id)}</span>],
                                ['Opened', formatDateTime(current.opened_at)],
                                ['Closed', current.closed_at ? formatDateTime(current.closed_at) : '—'],
                            ]}
                        />
                    </Panel>

                    <Panel title="Shifts in this day">
                        {shifts.failure && (
                            <ErrorAlert
                                message={failureMessage(shifts.failure, 'The shifts could not be loaded.')}
                                onRetry={[401, 403].includes(shifts.failure.status) ? undefined : shifts.reload}
                                onSignIn={shifts.failure.status === 401 ? signIn : undefined}
                            />
                        )}
                        {shifts.loading && !shifts.data && !shifts.failure && <div className="h-12 animate-pulse rounded bg-slate-950" aria-busy="true" />}
                        {shifts.data && shifts.data.data.length === 0 && <p className="text-sm text-slate-500">No shift was opened in this day.</p>}
                        {shifts.data && shifts.data.data.length > 0 && (
                            <ul className="divide-y divide-slate-800/70">
                                {shifts.data.data.map((shift) => (
                                    <li key={shift.id} className="flex flex-wrap items-center gap-x-5 gap-y-1 py-2">
                                        <Link to={`/admin/shifts/${shift.id}`} className="font-mono text-[12px] text-emerald-400 hover:underline">
                                            {formatDateTime(shift.opened_at)}
                                        </Link>
                                        <span className="w-16 shrink-0">
                                            <DayStatusBadge status={shift.status} />
                                        </span>
                                        <span className="font-mono text-[12px] text-slate-400" title={shift.cashier_id}>
                                            cashier {shortId(shift.cashier_id)}
                                        </span>
                                        <span className="font-mono text-[12px] text-slate-400">
                                            declared <Money value={shift.declared_cash} />
                                        </span>
                                        <span className="font-mono text-[12px]">
                                            <Variance value={shift.variance} />
                                        </span>
                                    </li>
                                ))}
                            </ul>
                        )}
                    </Panel>

                    {current.status === 'OPEN' && <p className="text-sm text-slate-400">This day is still open. Its Z-reading is produced when the day is closed at the POS.</p>}

                    {zReading.failure && (
                        <ErrorAlert
                            message={failureMessage(zReading.failure, 'The Z-reading could not be loaded.')}
                            onRetry={[401, 403].includes(zReading.failure.status) ? undefined : zReading.reload}
                            onSignIn={zReading.failure.status === 401 ? signIn : undefined}
                        />
                    )}
                    {zReading.loading && !zReading.data && !zReading.failure && <div className="h-40 animate-pulse rounded bg-slate-900" aria-busy="true" aria-label="Loading Z-reading" />}
                    {zReading.data && <ZReadingPanel reading={zReading.data} />}
                </>
            )}
        </AdminLayout>
    );
}
