export default {
    slug: 'glossary',
    category: 'trouble',
    reference: true,
    title: 'Words you will meet',
    summary: 'Plain-language meanings of the terms TindaFlow uses.',
    roles: ['CASHIER', 'MANAGER', 'ADMIN'],
    minutes: 5,
    steps: [
        { title: 'Terminal (and “enrolled”)', body: 'A **terminal** is one till. A browser can only sell once an admin has **enrolled** it as a terminal with a one-time token. Every sale is recorded against the terminal it came from.' },
        { title: 'Shift', body: 'A **shift** is one cashier’s time at a till, from **Open shift** to **Close shift**. Only one shift can be open on a till at a time.' },
        { title: 'Opening cash, expected cash, counted cash, variance', body: '**Opening cash** is what is in the drawer when you start. **Expected cash** is what the system works out should be there: opening cash plus cash sales, minus cash refunds, plus cash in, minus cash out. **Counted cash** is what you count. **Variance** is counted minus expected. Zero is balanced, negative is short.' },
        { title: 'Business day (fiscal day)', body: 'A terminal’s **business day** runs from the first shift that opens it to the end-of-day close. Closing it produces the Z-reading.' },
        { title: 'X-reading', body: 'A reading of a shift so far. It does not close the shift and changes nothing. Take one whenever you need to see where the shift stands.' },
        { title: 'Z-reading', body: 'The end-of-day figures produced when the business day is closed. They are fixed for good and never recalculated. Each closed day gets the next Z-reading number.' },
        { title: 'Void', body: 'Cancels a whole sale and puts every item back in stock. It only works while the sale’s business day is still open. A cashier requests it and a manager approves it.' },
        { title: 'Refund', body: 'Returns some or all of the items in a sale and pays money back. It can be done after the business day is closed. A cashier requests it and a manager approves it.' },
        { title: 'Invoice, transaction number and invoice number', body: 'Every completed sale has a **transaction number** and an **invoice number**. Invoice numbers come from an **invoice series**, count up and are never reused. A printed copy is marked **REPRINT — COPY**.' },
        { title: 'Invoice series and fiscal installation', body: 'A **fiscal installation** records the software set-up that issues your invoices. Each terminal must be assigned to exactly one. An **invoice series** is the numbering the installation uses, with a code, a prefix and a starting number. Only one series can be active for an installation.' },
        { title: 'Tax class', body: 'How a product is taxed. **VATABLE** is sold with VAT. **VAT EXEMPT** is sold without VAT. **ZERO RATED** is sold at a 0% VAT rate. **NON-VAT** is not subject to VAT. The **tax registration** says whether the store itself is VAT or non-VAT.' },
        { title: 'SKU and barcode', body: 'A **SKU** is your own unique code for a product. A **barcode** is the number a scanner reads. Both can find a product at the till.' },
        { title: 'Unit, pack and reorder level', body: 'Stock is counted in a product’s **unit**, such as pieces. A **pack**, such as a case of 24, says how many units it holds. The **reorder level** is the quantity at or below which a product is flagged as low.' },
        { title: 'Location', body: 'A place where stock is kept, for example Store shelf or Backroom. Sales take stock from the **default** location.' },
        { title: 'Audit log and electronic journal', body: 'The **audit log** records who did what and when. The **electronic journal** keeps a snapshot of every invoice, void, refund, reading and cash movement. Neither can be changed or deleted.' },
        { title: 'Role', body: 'A **Cashier** rings up sales and requests voids and refunds. A **Manager** also decides on voids and refunds, gives discounts, handles stock and the catalog, and reads reports. An **Admin** can do everything, including users, terminals and store set-up.' },
    ],
    done: 'Still unsure about a word? Ask a manager, and read the guide for the screen you are on.',
    next: ['troubleshooting'],
};
